In [1]:
from sklearn.datasets import load_iris
from icecream import ic
from collections import Counter
import numpy as np
import pandas as pd

## 基于KNN的分类和回归原理

In [2]:
iris_x = load_iris()['data']
iris_y = load_iris()['target']
iris_x, iris_y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [5]:
list(zip(iris_x, iris_y))

[(array([5.1, 3.5, 1.4, 0.2]), 0),
 (array([4.9, 3. , 1.4, 0.2]), 0),
 (array([4.7, 3.2, 1.3, 0.2]), 0),
 (array([4.6, 3.1, 1.5, 0.2]), 0),
 (array([5. , 3.6, 1.4, 0.2]), 0),
 (array([5.4, 3.9, 1.7, 0.4]), 0),
 (array([4.6, 3.4, 1.4, 0.3]), 0),
 (array([5. , 3.4, 1.5, 0.2]), 0),
 (array([4.4, 2.9, 1.4, 0.2]), 0),
 (array([4.9, 3.1, 1.5, 0.1]), 0),
 (array([5.4, 3.7, 1.5, 0.2]), 0),
 (array([4.8, 3.4, 1.6, 0.2]), 0),
 (array([4.8, 3. , 1.4, 0.1]), 0),
 (array([4.3, 3. , 1.1, 0.1]), 0),
 (array([5.8, 4. , 1.2, 0.2]), 0),
 (array([5.7, 4.4, 1.5, 0.4]), 0),
 (array([5.4, 3.9, 1.3, 0.4]), 0),
 (array([5.1, 3.5, 1.4, 0.3]), 0),
 (array([5.7, 3.8, 1.7, 0.3]), 0),
 (array([5.1, 3.8, 1.5, 0.3]), 0),
 (array([5.4, 3.4, 1.7, 0.2]), 0),
 (array([5.1, 3.7, 1.5, 0.4]), 0),
 (array([4.6, 3.6, 1. , 0.2]), 0),
 (array([5.1, 3.3, 1.7, 0.5]), 0),
 (array([4.8, 3.4, 1.9, 0.2]), 0),
 (array([5. , 3. , 1.6, 0.2]), 0),
 (array([5. , 3.4, 1.6, 0.4]), 0),
 (array([5.2, 3.5, 1.5, 0.2]), 0),
 (array([5.2, 3.4, 1

In [43]:
def knn(x, y, query, k=3, clf=True):
    history = {tuple(x_): y_ for x_, y_ in zip(x, y)}
#     for x_y_ in history.items():
#         print(x_y_)
#         break
    neighbors = sorted(history.items(), key=lambda x_y: np.sum((np.array(x_y[0]) - np.array(query)) ** 2))[:k]
    neighbors_y = [y for x, y in neighbors]
    
    if clf:
        # 分类
        return Counter(neighbors_y).most_common(1)[0][0]
    else:
        # 回归
        return np.mean(neighbors_y)

In [44]:
knn(iris_x, iris_y, [3.3, 5.1, 1.5, 0.3], 3)

0