# PyTorch基础练习

In [1]:
import numpy as np
import torch

In [2]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [3]:
points = 100
points = np.arange(points)
print(points)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [4]:
np.random.shuffle(points)
print(points)

[49 91 48  0 22 99 24  6 86 82 89 93 23 67 46 70 64 15 36 42 31 60 56 50
 95 33 83  1 55 85 39 80  8 32 97 35 75  5 52 71 72 13 92 78 87 74 37 90
  9 19 65 44 84 88 47 20 96  7 81 27 11 34 28 53 41 73 30 58 98 66 59 16
 63 25 57 51 12 76 18 21 17 38 61 40 62 14 26 54 69 43 77 45 79 10  3 94
  4  2 68 29]


In [5]:
result = torch.zeros(3)
result

tensor([0., 0., 0.])

In [6]:
a = np.ones(3)
x = torch.from_numpy(a)
print(x)

tensor([1., 1., 1.], dtype=torch.float64)


In [7]:
x = torch.Tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [8]:
print(x.size())

torch.Size([3, 3])


In [9]:
print(x.view(x.size(0), -1))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [14]:
x.permute(1,0)

tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])

In [15]:
print(x.pow(-1.0))

tensor([[1.0000, 0.5000, 0.3333],
        [0.2500, 0.2000, 0.1667],
        [0.1429, 0.1250, 0.1111]])


In [16]:
print(x.pow(2.0))

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [20]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [21]:
print(x.sum(dim=0))

tensor([12., 15., 18.])


In [18]:
print(x.sum(dim=1))

tensor([ 6., 15., 24.])


In [19]:
torch.sum(x, 0)

tensor([12., 15., 18.])

In [22]:
torch.sum(x, 1)

tensor([ 6., 15., 24.])

In [25]:
temp = x.sum(dim=1).pow(-1.0)
temp

tensor([0.1667, 0.0667, 0.0417])

In [26]:
temp.diag_embed()

tensor([[0.1667, 0.0000, 0.0000],
        [0.0000, 0.0667, 0.0000],
        [0.0000, 0.0000, 0.0417]])

In [27]:
t = torch.rand(2,4,3,5)
t

tensor([[[[0.9570, 0.1000, 0.1614, 0.8228, 0.0227],
          [0.3665, 0.4578, 0.8994, 0.0187, 0.0530],
          [0.4133, 0.9875, 0.3627, 0.5291, 0.2068]],

         [[0.2388, 0.1913, 0.7590, 0.3333, 0.5477],
          [0.6668, 0.5423, 0.8180, 0.2307, 0.6849],
          [0.7704, 0.2172, 0.4305, 0.6080, 0.1693]],

         [[0.4274, 0.7745, 0.8043, 0.6123, 0.4237],
          [0.6435, 0.6862, 0.1667, 0.9500, 0.0792],
          [0.7268, 0.8504, 0.3084, 0.4645, 0.7079]],

         [[0.1274, 0.4846, 0.8230, 0.9182, 0.4240],
          [0.7538, 0.6278, 0.9341, 0.5141, 0.8125],
          [0.3475, 0.1317, 0.2730, 0.9145, 0.0737]]],


        [[[0.7346, 0.5792, 0.6894, 0.4773, 0.1748],
          [0.0203, 0.9293, 0.4438, 0.6921, 0.6238],
          [0.2376, 0.6566, 0.2980, 0.4800, 0.6499]],

         [[0.5124, 0.0787, 0.2053, 0.7373, 0.4591],
          [0.2702, 0.3597, 0.1884, 0.8664, 0.3131],
          [0.2819, 0.5917, 0.7772, 0.1534, 0.8633]],

         [[0.9757, 0.2283, 0.4319, 0.9459, 0.5097]

In [29]:
a = np.random.rand(2,4,3,5)
a

array([[[[0.10716524, 0.9166782 , 0.04635848, 0.56198336, 0.02087592],
         [0.32538558, 0.2566032 , 0.74712282, 0.27949765, 0.55637071],
         [0.45917704, 0.46200676, 0.35505895, 0.90579274, 0.00592826]],

        [[0.79821837, 0.89935362, 0.82784687, 0.8481568 , 0.04374487],
         [0.48190592, 0.83751444, 0.83975106, 0.75382528, 0.1778663 ],
         [0.80712501, 0.56656216, 0.47737137, 0.35943032, 0.57691504]],

        [[0.07097756, 0.50812015, 0.94485797, 0.90791516, 0.31363903],
         [0.23529796, 0.74417538, 0.89399947, 0.03866162, 0.85082522],
         [0.41271141, 0.14563397, 0.73671574, 0.94435268, 0.69632328]],

        [[0.86788122, 0.0797183 , 0.81085737, 0.55772061, 0.30719923],
         [0.55942629, 0.69383751, 0.39787506, 0.8646965 , 0.13277082],
         [0.3393943 , 0.50875231, 0.55614429, 0.83132286, 0.42590987]]],


       [[[0.42029187, 0.8493276 , 0.91402683, 0.87422618, 0.64793644],
         [0.75645253, 0.81393353, 0.3637415 , 0.08263176, 0.8041526

In [30]:
print(t.shape)

torch.Size([2, 4, 3, 5])


In [32]:
print(t.size())

torch.Size([2, 4, 3, 5])


In [33]:
print(a.shape)

(2, 4, 3, 5)


In [36]:
print(a.size)

120


In [37]:
print(t.stride())

(60, 15, 5, 1)


In [38]:
print(t.stride(0))

60


In [39]:
print(t.stride(1))

15


In [40]:
print(t.stride(2))

5


In [41]:
print(t.stride(3))

1


In [42]:
print(x.narrow(0,0,3))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [43]:
print(x.narrow(0,1,2))

tensor([[4., 5., 6.],
        [7., 8., 9.]])


In [44]:
print(x.narrow(1,1,2))

tensor([[2., 3.],
        [5., 6.],
        [8., 9.]])


In [45]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [46]:
print(x.narrow(-1, 2, 1))

tensor([[3.],
        [6.],
        [9.]])


In [48]:
x = torch.zeros(3)
x

tensor([0., 0., 0.])

In [49]:
a = torch.Tensor([[[1,2,3], [4,5,6]]])
b = torch.Tensor([1,2,3,4,5,6])

In [50]:
print(type(a))

<class 'torch.Tensor'>


In [51]:
print(a.view(1,6))

tensor([[1., 2., 3., 4., 5., 6.]])


In [52]:
print(b.view(1,6))

tensor([[1., 2., 3., 4., 5., 6.]])


In [53]:
print(a.view(3,2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [54]:
x

tensor([0., 0., 0.])

In [55]:
t = torch.Tensor([[1,2,3], [4,5,6],[7,8,9]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [56]:
t.sum(dim=0)

tensor([12., 15., 18.])

In [57]:
t.sum(dim=1)

tensor([ 6., 15., 24.])

In [58]:
a

tensor([[[1., 2., 3.],
         [4., 5., 6.]]])

In [59]:
temp = a.view(3,2)

In [60]:
temp

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [62]:
print(temp.size())

torch.Size([3, 2])


In [63]:
print(temp.view(1, -1))

tensor([[1., 2., 3., 4., 5., 6.]])


In [64]:
print(temp.view(-1, 1))

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])
