In [1]:
# 使用numpy实现Boston房价预测
import numpy as np
from sklearn.datasets import load_boston
from sklearn.utils import shuffle, resample

In [2]:
# 数据加载
data = load_boston()
X_ = data['data']
y = data['target']
print(X_)
print(len(X_)) # 506

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
506


/Users/fenghaoguo/opt/anaconda3/envs/p39/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Ca

In [3]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [4]:
y = y.reshape(y.shape[0],1)
y

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2],
       [28.7],
       [22.9],
       [27.1],
       [16.5],
       [18.9],
       [15. ],
       [18.9],
       [21.7],
       [20.4],
       [18.2],
       [19.9],
       [23.1],
       [17.5],
       [20.2],
       [18.2],
       [13.6],
       [19.6],
       [15.2],
       [14.5],
       [15.6],
       [13.9],
       [16.6],
       [14.8],
       [18.4],
       [21. ],
       [12.7],
       [14.5],
       [13.2],
       [13.1],
       [13.5],
       [18.9],
       [20. ],
       [21. ],
       [24.7],
       [30.8],
       [34.9],
       [26.6],
       [25.3],
       [24.7],
       [21.2],
       [19.3],
       [20. ],
       [16.6],
       [14.4],
       [19.4],
       [19.7],
       [20.5],
       [25. ],
       [23.4],
       [18.9],
       [35.4],
       [24.7],
       [31.6],
       [23.3],
       [19.6],
       [18.7],
       [16. ],
       [22.2],
       [25. ],
       [33. ],
       [23.5],
       [19

In [5]:
# 数据规范化
X_ = (X_ - np.mean(X_, axis=0)) / np.std(X_, axis=0)
print(X_)

[[-0.41978194  0.28482986 -1.2879095  ... -1.45900038  0.44105193
  -1.0755623 ]
 [-0.41733926 -0.48772236 -0.59338101 ... -0.30309415  0.44105193
  -0.49243937]
 [-0.41734159 -0.48772236 -0.59338101 ... -0.30309415  0.39642699
  -1.2087274 ]
 ...
 [-0.41344658 -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.98304761]
 [-0.40776407 -0.48772236  0.11573841 ...  1.17646583  0.4032249
  -0.86530163]
 [-0.41500016 -0.48772236  0.11573841 ...  1.17646583  0.44105193
  -0.66905833]]


In [6]:
np.random.seed(33)

n_features = X_.shape[1]
n_hidden = 16
w1 = np.random.randn(n_features, n_hidden)
b1 = np.zeros(n_hidden)
w2 = np.random.randn(n_hidden, 1)
b2 = np.zeros(1)

In [7]:
# relu函数
def Relu(x):
    result = np.where(x<0,0,x)
    return result

In [8]:
def MSE_loss(y, y_hat):
    return np.mean(np.square(y_hat - y))

def Linear(X, W1, b1):
    result = X.dot(W1) + b1
    return result

In [9]:
# 设置学习率
learning_rate = 1e-5

# 5000次迭代
for t in range(1000):
    # 前向传播，计算预测值y
    l1 = Linear(X_, w1, b1)
    s1 = Relu(l1)
    #s1 = np.maximum(l1, 0)
    #print('s1=', s1.shape) #(506, 10)
    #print('w2=', w2.shape) #(506, 10)
    #print('s1.T=', s1.T.shape) #(10, 506)
    y_pred = Linear(s1, w2, b2)
    #y_pred = l2 = s1.dot(w2) + b2
    #print('y_pred=', y_pred.shape) #(506, 1)
    #print('y=', y.shape) #(506, 1)


    #temp = X.dot(w1)
    #temp_relu = np.maximum(temp, 0)
    #y_pred = temp_relu.dot(w2)

    # 计算损失函数
    loss = MSE_loss(y, y_pred)
    #print(y_pred)
    #print(y_pred.shape)
    print(t, loss)

    # 反向传播，基于loss 计算w1和w2的梯度
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = s1.T.dot(grad_y_pred) #(10, 506) * (506, 506)
    #print('grad_w2=', grad_w2.shape) #(10, 506)
    #print('grad_y_pred=', grad_y_pred.shape) #(506, 506)
    #print('w2.T=', w2.T.shape) #(1, 10)
    grad_temp_relu = grad_y_pred.dot(w2.T) #(506, 506),  (1, 10)
    #grad_temp = grad_temp_relu.copy()
    grad_temp_relu[l1<0] = 0
    grad_w1 = X_.T.dot(grad_temp_relu)

    # 更新权重
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2
print('w1={} \n w2={}'.format(w1, w2))

0 297.03368368729946
1 169.2953183680402
2 104.58561106663221
3 75.38551670789849
4 63.149027978904186
5 57.3627041743113
6 53.79808160928698
7 51.16171091374708
8 49.04162760502336
9 47.25436617515906
10 45.705472776607365
11 44.35285047779679
12 43.13524036841349
13 42.02412008905917
14 41.007375342039445
15 40.070826876597444
16 39.1992778964584
17 38.387373955703346
18 37.62906124649611
19 36.92369244486195
20 36.25320011011349
21 35.61765752123139
22 35.01617079653234
23 34.44986709262706
24 33.90448090118872
25 33.38550968677576
26 32.888819199202366
27 32.41323276065982
28 31.95096375866202
29 31.49898542765378
30 31.064567035597797
31 30.644399639065124
32 30.239182258216726
33 29.84257752736654
34 29.460119534232916
35 29.089948421563516
36 28.73356191517718
37 28.37770665321904
38 28.02778153712415
39 27.68886135703589
40 27.36119843135018
41 27.041314929735204
42 26.729826932200307
43 26.42970971813895
44 26.14176747376231
45 25.863223219992175
46 25.594511700701467
47 25.33

552 10.566550622436733
553 10.561115733662728
554 10.555695156091867
555 10.550459721345412
556 10.54541755735474
557 10.539999709395772
558 10.534615686617176
559 10.529272777728414
560 10.52395345095644
561 10.518750810392206
562 10.51388673079002
563 10.508544163485297
564 10.503234408191911
565 10.497959030944148
566 10.492741864070434
567 10.487662353439957
568 10.482725331478983
569 10.476937491599962
570 10.471201683410005
571 10.465520976716636
572 10.45985186828685
573 10.454213531898585
574 10.448959235827328
575 10.443459045295858
576 10.43778453172733
577 10.432203573008081
578 10.426663586116868
579 10.421073454985587
580 10.415806012140118
581 10.410091532947705
582 10.404464063458535
583 10.398861597378252
584 10.393295402200343
585 10.387935520129748
586 10.382762354643159
587 10.377211249196943
588 10.371688002520782
589 10.366214742819073
590 10.360767961789811
591 10.355474261631729
592 10.35041620344609
593 10.344954628366331
594 10.339548306480488
595 10.3341719007