## 词向量的过程

In [1]:
!ls ../../../data_bak/article_9k.txt

../../../data_bak/article_9k.txt


In [2]:
CONTENT = open('../../../data_bak/article_9k.txt').read()

In [3]:
sample_content = CONTENT[:1000]

In [4]:
import jieba

In [5]:
def cut(string): return list(jieba.cut(string))

In [6]:
sample_words = cut(sample_content)

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/19/dgxwsbgd76728hx577833nx00000gn/T/jieba.cache
Loading model cost 0.589 seconds.
Prefix dict has been built successfully.


In [7]:
vocabulary = set(sample_words)

In [8]:
len(vocabulary)

368

## One-hot 编码

In [9]:
one_hot_matrix = [[0] * len(vocabulary)  for _ in range(len(vocabulary)) ]

word_to_index = {}

index_to_word = {}

In [10]:
for i, v in enumerate(vocabulary):
    one_hot_matrix[i][i] = 1
    word_to_index[v] = i
    index_to_word[i] = v

In [11]:
word_to_index['我们']

365

In [12]:
import numpy as np

In [13]:
word_to_index['小米']

309

In [14]:
word_to_index['手机']

241

In [15]:
len(one_hot_matrix), len(one_hot_matrix[0])

(368, 368)

## 我们要求出来 embedding的词向量

In [16]:
vec_dim = 10

In [17]:
import random

In [18]:
random_matrix = np.random.rand(len(vocabulary), vec_dim)
random_matrix.shape

(368, 10)

In [19]:
random_matrix

array([[0.18863134, 0.62094547, 0.52126211, ..., 0.50405184, 0.56420719,
        0.80942606],
       [0.29702249, 0.43647415, 0.47062269, ..., 0.94804914, 0.85062266,
        0.20580182],
       [0.57715777, 0.29649987, 0.5390165 , ..., 0.2264612 , 0.66021504,
        0.8578246 ],
       ...,
       [0.92607973, 0.61311329, 0.20634894, ..., 0.64191519, 0.99525468,
        0.68018808],
       [0.00437431, 0.1978559 , 0.47709327, ..., 0.6125092 , 0.83759357,
        0.74885168],
       [0.02498121, 0.68197128, 0.91619322, ..., 0.50812967, 0.51516776,
        0.53104119]])

In [20]:
one_hot_matrix[156]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [21]:
np.where(one_hot_matrix[156])

(array([156]),)

In [22]:
xiaom_vec = np.dot(np.array(one_hot_matrix[156]), random_matrix) # 小米对应的初始化向量

In [23]:
phone_vec = np.dot(np.array(one_hot_matrix[19]), random_matrix) # 手机对应的初始化向量

In [24]:
## 这两个词向量刚开始是随机的

In [25]:
xiaom_vec

array([0.64017676, 0.32507542, 0.97264232, 0.26883495, 0.9467337 ,
       0.68380131, 0.10432973, 0.45462376, 0.11009026, 0.12090211])

## 然后，会初始化一个叫做hidden_layer的一个矩阵

+ xiaom_vec => (1, 10)
+ hidden_layer => (10, len(vocabulary))

In [26]:
hiden_layer = np.random.rand(vec_dim, len(vocabulary))

In [27]:
output1 = np.dot(xiaom_vec, hiden_layer).shape

In [28]:
output2 = np.dot(phone_vec, hiden_layer).shape

## 如何output1和output2的值是相近的
## 那么是不是说，xiaom_vec 和 phone_vec的值是相近的？ 

## 假设，“小米”和 “手机”的意思是接近的； 
## 那么xiaom_vec 和 phone_vec 我们期望的结果应该是相似的
## 那么，output1 和 output2 的结果应该是相似的的

## 但是，现在，output1和output的结果未必是相似的

##  ORACLE: 当“单词W1”和“单词W2”意思相近的时候，“output1”和“ouput2”的结果也应该相似

## 我们的语言学家告诉我们，如果“w1”和“w2”的单词意思相似，那么就会有什么结果呢？w1周围的单词，和w2周围的单词，应该是类似的~ 

## 要把output 和它 周围的单词 链接起来，产生关系

In [29]:
[1, 2, 4] #=> 一组东西的概率

[1, 2, 4]

In [30]:
[3, 4, -1] #=> 一组东西的概率

[3, 4, -1]

In [31]:
"桃子 苹果 西瓜" 

'桃子 苹果 西瓜'

In [32]:
def normalize(X):
    return [x / sum(X) for x in X]

In [33]:
def softmax(X):
    X -= np.max(X)
    
    exps = [np.exp(x) for x in X]
    
    return [e / sum(exps) for e in exps]

In [34]:
def caculate_fruit_pro(x):
    """
    return 
    [0, 0, 1] # 属于每个类别的概率：[属于桃子的概率是0%, 属于苹果的是0%， 属于西瓜的是100%]
    [0, 1, 0] # 属于每个类别的概率：[属于桃子的概率是0%, 属于苹果的是100%， 属于西瓜的是0%]
    [1, 0, 0] # 属于每个类别的概率：[属于桃子的概率是100%, 属于苹果的是0%， 属于西瓜的是0%]
    """
    
    logits = [0.99, 0.18, 0.48] # 每个类别的得分~
    
#    probabilities = normalize(logits)
    
    probabilities = softmax(logits)
    
    return probabilities

In [35]:
caculate_fruit_pro([9, 1, 1, 3, 1, 3, 1])

[0.4889130065244961, 0.2174968946337315, 0.2935900988417724]

$$ cross-entropy(y_{true}, \hat{y}) = -\sum_i^n{y_i^{true}}{log(\hat{y_i})}$$

In [36]:
def cross_entropy(y_true, y_hat):
    return -1 * sum(y_t_i * np.log(y_hat_i) for y_t_i, y_hat_i in zip(y_true, y_hat))

## 假设，有一个图片，它对于的答案是桃子

## 那么，我们期望的caculate_fruit_pro的结果应该是[1, 0, 0]
## 有两个函数，一个算出来的是 [0.7, 0.2, 0.1]
## 一个算出来的是 [0.6, 0.2, 0.2]

In [37]:
cross_entropy([1, 0, 0], [0.8, 0.1, 0.1])

0.2231435513142097

In [38]:
cross_entropy([1, 0, 0], [0.7, 0.2, 0.1])

0.35667494393873245

In [39]:
cross_entropy([1, 0, 0], [0.6, 0.2, 0.2])

0.5108256237659907

In [40]:
cross_entropy([1, 0, 0], [0.5, 0.3, 0.2])

0.6931471805599453

1. 小米， 手机 单词 获得它的one-hot值
+ one-hot值，获得了它们随机的 xiaom_vec, phone_vec
+ xiaom_vec, phone_vec 和 hidden_layer做点积
+ output1, output2
+ output1, output2 => softmax(output1), softmax(output2)
+ 计算cross_entropy(”小米“周围的单词的label, softmax(output1))
+ 计算cross_entropy(“手机”周围的单词的label, softmax(output2))

6， 7步的结果： 如何第一步的两个单词结果是相似的，那么，6，7步的结果也应该是相似的

## 有一种叫做反向传播的机制

当我们知道，softmax(x) 之后应该是某个值的时候，但是实际上它不是这个值，我们计算机会做更新，把x，和x相关的所有东西，进行更新，然后一次次的让
softmax(x)的值更接近我们期望的值，这个“反向传播”，就是深度学习的核心

## 词向量的过程

对于单词 $w_1$ 和 $w_2$ , 如果$w_1$和$w_2$的单词意思相似，那么$w_1$和$w_2$周围的单词，也应该是相似的，
这个是语言学家告诉我们的

根据$w_1$和$w_2$，我们能得到他们随机初始化的 $vec_1, vec_2$

$vec_1 \cdot hidden_m => output_1$

$vec_2 \cdot hidden_m => output_2$

softmax(output1) 赋予的含义是： $w_1$周围出现什么单词

softmax(output2) 赋予的含义是： $w_2$周围出现什么单词

$loss_1$ = cross_entropy($w_1$周围真正的单词的label, softmax(output1))

$loss_2$ = cross_entropy($w_2$周围真正的单词的label, softmax(output2))

我们期望的是，loss => 0 

我们使用“反向传播”算法，能够逐渐让“loss1”和“loss2”变成0

## 当loss1和loss2逐渐变成0的时候

那么这个时候，output1和output2的值也是接近的

output1和output2的值是接近的，意味着“vec_1”和“vec_2”的值也是接近的

所以，得到了两个值接近的单词向量 "vec_1", "vec_2" 当 他们对应的单词 "w1" 和 “w2” 意思接近的时候